apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: wechat
  namespace: monitor
  labels:
    alertmanagerConfig: alertmanager
spec:
  route:
    group_by: ['job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: 'wechat'
    routes:
      - receiver: 'wechat'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
  receivers:
    - name: 'wechat'
      wechatConfigs:
        - apiURL: 'http://wechatserver:8080/'
          corpID: 'wechat-corpid'
          apiSecret:
            name: 'wechat-config'
            key: 'apiSecret'
