alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik-internet-vpn"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-common-headers@kubernetescrd
    hosts:
      - "alertmanager.internal-devops.${TARGET_ENV}.npool.top"
    path: /
  config:
    route:
      group_by: [ 'job' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'wechat'
      routes:
      - receiver: 'wechat'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
    receivers:
      - name: 'wechat'
        wechat_config:
        - send_resolved: false
          api_url: http://webhook-dingtalk.monitor.svc.cluster.local:8060/dingtalk/webhook1/send

grafana:
  adminPassword: ${GRAFANA_PASSWORD}
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik-internet-vpn"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-common-headers@kubernetescrd
    hosts:
      - "grafana.internal-devops.${TARGET_ENV}.npool.top"
    path: /
  image:
    repository: grafana/grafana
    tag: "8.5.5"

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik-internet-vpn"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-common-headers@kubernetescrd
    hosts:
      - "prometheus.internal-devops.${TARGET_ENV}.npool.top"
    path: /