apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: go-grpc-rule
  namespace: monitor
spec:
  groups:
    - name: redis-export
      rules:
        - alert: RedisDown
          expr: redis_up{service="prometheus-redis-exporter"} == 0
          for: 2m
          labels:
            severity: error
          annotations:
            summary: Redis instance {{ "{{ $labels.instance }}" }} down
            description: Redis instance {{ "{{ $labels.instance }}" }} is down.
        - alert: RedisMemoryHigh
          expr: >
            redis_memory_used_bytes{service="prometheus-redis-exporter"} * 100
            /
            redis_memory_max_bytes{service="prometheus-redis-exporter"}
            > 90 <= 100
          for: 2m
          labels:
            severity: error
          annotations:
            summary: Redis instance {{ "{{ $labels.instance }}" }} is using too much memory
            description: |
              Redis instance {{ "{{ $labels.instance }}" }} is using {{ "{{ $value }}" }}% of its available memory.
        - alert: RedisKeyEviction
          expr: |
            increase(redis_evicted_keys_total{service="prometheus-redis-exporter"}[5m]) > 0
          for: 1s
          labels:
            severity: error
          annotations:
            summary: Redis instance {{ "{{ $labels.instance }}" }} has evicted keys
            description: |
              Redis instance {{ "{{ $labels.instance }}" }} has evicted {{ "{{ $value }}" }} keys in the last 5 minutes.
