redisAddress: redis://redis.kube-system.svc.cluster.local:6379
image:
  tag: alpine
serviceMonitor:
  enabled: true
  namespace: monitor
  labels:
    release: prometheus
auth:
  enabled: true
  secret:
    name: redis-password
    key: "password"
nodeSelector:
  ${NODE_SELECTOR_LABEL_KEY}: ${NODE_SELECTOR_LABEL_VALUE}