serviceMonitor:
  enabled: true
  namespace: monitor
  additionalLabels:
      release: prometheus
nodeSelector:
  ${NODE_SELECTOR_LABEL_KEY}: ${NODE_SELECTOR_LABEL_VALUE}
mysql:
  host: "mysql.kube-system"
  user: "mysql_exporter"
  port: 3306
  existingPasswordSecret:
    name: "mysql-exporter-password-secret"
    key: "password"
config:
  # Allow to set specifc options on the exporter
  logLevel: debug